/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pdfform;

import java.io.IOException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        
        try {
            App.testExtracting();
            // App.testFilling();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void testExtracting() throws IOException {
        String src = "../assets/imm5645e.pdf";
        
        Path srcPath = Paths.get(src);
        Path destItext = srcPath.getParent().resolve(srcPath.getFileName() + "_extracted_itext");
        Path destOpenpdf = srcPath.getParent().resolve(srcPath.getFileName() + "_extracted_openpdf");
        Files.createDirectories(destItext);
        Files.createDirectories(destOpenpdf);

        ExtractorUsingItext.extractAcroformFields(src, destItext.resolve("acrofields.txt").toString());
        ExtractorUsingOpenpdf.extractAcroformFields(src, destOpenpdf.resolve("acrofields.txt").toString());

        ExtractorUsingItext.extractXfa(src, destItext.toString());
        ExtractorUsingOpenpdf.extractXfa(src, destOpenpdf.toString());
    }

    public static void testFilling() throws FileNotFoundException {
        String src = "../assets/imm5645e.pdf";
        Path srcPath = Paths.get(src);

        String destItext = src.replace(".pdf", "_edited_itext.pdf");
        String destOpenpdf = src.replace(".pdf", "_edited_openpdf.pdf");

        String xmlItext = srcPath.getParent()
            .resolve(srcPath.getFileName() + "_extracted_itext")
            .resolve("xfa_datasets.xml").toString();
        String xmlOpenpdf = srcPath.getParent()
            .resolve(srcPath.getFileName() + "_extracted_openpdf")
            .resolve("xfa_datasets.xml").toString();
        
        FillerUsingItext.fillXfaData(src, destItext, new FileInputStream(xmlItext));
        FillerUsingOpenpdf.fillXfaData(src, destOpenpdf, new FileInputStream(xmlOpenpdf));
    }
}
